service: cors-python
configValidationMode: off
provider:
  name: scaleway
  runtime: python310
  env:
    test: test

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    handler: handler.handle
