service: Programmez-Scaleway
configValidationMode: off

provider:
  name: scaleway
  runtime: node16
  # Global Environment variables - used in every functions
  secret:
    ACCESS_KEY: <bucket scw access key>
    ACCESS_KEY_ID: <bucket scw access key id>
    SOURCE_BUCKET: <source bucket name>
    DESTINATION_BUCKET: <bucket name>
    S3_ENDPOINT_URL: http://s3.fr-par.scw.cloud
    TRANSFORM_URL: <image transform url>
  # the path to the credentials file needs to be absolute
  scwToken: <your scw token>
  scwProject: <project ID>
  scwRegion: fr-par


plugins:
  - serverless-scaleway-functions

patterns:
    - '!.gitignore'
    - '!.git/**'

functions:
  imagetransform:
    handler: ImageTransform.handle
    memoryLimit: 1024
    minScale: 0
    env:
      RESIZED_WIDTH: '300'
  bucketscan:
    handler: BucketScan.handle
    memoryLimit: 1024
    minScale: 0
    events:
     - schedule:
         rate: '0 * * * *'